[package]
name = "aws_lambda_events"
version = "0.7.2"
description = "AWS Lambda event definitions"
authors = [
  "Christian Legnitto <christian@legnitto.com>",
  "Sam Rijs <srijs@airpost.net>",
  "David Calavera <dcalaver@amazon.com>"
]
license = "MIT"
homepage = "https://github.com/LegNeato/aws-lambda-events"
repository = "https://github.com/LegNeato/aws-lambda-events"
readme = "README.md"
keywords = ["lambda", "aws", "amazon", "events", "S3"]
categories = ["api-bindings", "encoding", "web-programming"]

[dependencies]
base64 = "0.13"
http = "0.2"
http-body = "0.4"
http-serde = "^1"
serde = "^1"
serde_derive = "^1"
serde_with = { version = "^2", features = ["json"], optional = true }
serde_json = "^1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "^0.4.4", default-features = false, features = ["serde", "std"] }
query_map = { version = "^0.6", features = ["serde", "url-query"] }
flate2 = { version = "1.0.24", optional = true }

[dev-dependencies]
pretty_assertions = "1.3"

# There are two kinds of features, `static` and `generated`.
# The `static` features reference features that we manually implement in the crate.
# The `generated` features reference features generated by the codegen script.
[features]
default = ["generated", "static"]
static = ["alb", "apigw", "cloudwatch_events", "cloudwatch_logs", "cognito", "dynamodb", "kinesis", "kinesis_analytics", "s3", "s3_batch_job", "sns", "sqs"]
alb = []
apigw = []
cloudwatch_events = []
cloudwatch_logs = ["flate2"]
cognito = []
dynamodb = ["streams"]
kinesis = []
kinesis_analytics = ["kinesis"]
s3 = []
s3_batch_job = ["s3"]
sns = ["serde_with"]
sqs = ["serde_with"]

activemq = []
appsync = []
autoscaling = []
chime_bot = []
clientvpn = []
code_commit = []
codebuild = []
codedeploy = []
codepipeline = []
codepipeline_cloudwatch = []
codepipeline_job = []
config = []
connect = []
ecr_scan = []
firehose = []
iot = []
iot_1_click = []
iot_button = []
kafka = []
lambda_function_urls = []
lex = []
rabbitmq = []
ses = []
streams = []
generated = ["activemq", "appsync", "autoscaling", "chime_bot", "clientvpn", "code_commit", "codebuild", "codedeploy", "codepipeline_cloudwatch", "codepipeline_job", "config", "connect", "ecr_scan", "firehose", "iot", "iot_1_click", "iot_button", "kafka", "lambda_function_urls", "lex", "rabbitmq", "ses", "streams"]
